### ISSUE TITLE
[Feature request] Add option for passing user credentials

### ISSUE THREAD

**Issue by 74naUM2EMP** [FliegendeWurst/KIT-ILIAS-downloader#10]
I'm trying to call KIT-ILIAS-downloader multiple times in a script, but I don’t believe there is way to pass credentials automatically.
Currently you have to provide credentials every time (I don’t like using .iliaslogin because it saves the credentials to the disk).
With an extra option these could be reused.

Example: `KIT-ILIAS-downloader -j 8 -U “$user” -P “$pass” -o “$dir”`

**Comment by FliegendeWurst** [comment]
> I don’t like using .iliaslogin because it saves the credentials to the disk

You can make the `.iliaslogin` file a symbolic link to a file in `/tmp` or some other RAM-backed storage.

Still, I'll implement your suggested options soon. They are more convenient to use in a script.

**Comment by FliegendeWurst** [comment]
Implemented in 0.2.16.
