### ISSUE TITLE
[Feature Suggestion] Rename ILIAS Course Names in a Config File

### ISSUE THREAD

**Issue by thelukasprobst** [FliegendeWurst/KIT-ILIAS-downloader#12]
This would allow annoying folder names such as "0186800 - Höhere Mathematik II (Analysis) für die Fachrichtung Informatik" to be renamed "Höhere Mathematik II" or even "HM II" for the sake of clarity.

**Comment by taDachs** [comment]
What kind of format should that be? Just a plain INI file with ```previousname=newname```?

**Comment by FliegendeWurst** [comment]
Yes, INI or TOML would be fine.
