### ISSUE TITLE
[Feature Suggestion] Set a Maximum Download Speed or Files per Minutes

### ISSUE THREAD

**Issue by el14s7** [FliegendeWurst/KIT-ILIAS-downloader#13]
Since there are recent issiues that the ILIAS/Opencast plattform cant hold up with alle the download requests, we are asked to not use download-tools like this (https://ilias.studium.kit.edu/goto.php?target=wiki_wpage_34653_678113&client_id=produktiv).

I think it would great, if I could say "Only download 1 File/Minute" or not more than 10 MBit/sec, since I don't care if files are downloaded in 2 or 20 Minutes.

**Comment by FliegendeWurst** [comment]
Thanks for the suggestion. I'll implement rate limiting based on the number of allowed requests per time slice soon.  
Limiting download bandwidth isn't possible with the HTTP library I use: https://github.com/seanmonstar/reqwest/issues/1226.

**Comment by FliegendeWurst** [comment]
Implemented in dc02ec7a460bf96c4569839819f856205edd1274 (released in 0.2.18).

**Comment by funnym0nk3y** [comment]
But it should be still allowed with a rate limiter and at low load hours like early in the morning, right?
