### ISSUE TITLE
No \n in windows cmd

### ISSUE THREAD

**Issue by el14s7** [FliegendeWurst/KIT-ILIAS-downloader#14]
Since the intriduction of the progress indicator:
![image](https://user-images.githubusercontent.com/21080573/117668827-98bad280-b1a6-11eb-8c04-51689b2fb375.png)

It seems like there are no linebreaks anymore:

![image](https://user-images.githubusercontent.com/21080573/117668594-601af900-b1a6-11eb-90b7-5f700bb5f6fe.png)

**Comment by el14s7** [comment]
Thank you for that fast fix :)
May it be possible, that keyring is not working in the file you linked above?

**Comment by FliegendeWurst** [comment]
Good to hear that the update worked :+1:

> May it be possible, that keyring is not working in the file you linked above?

Yes. The file I linked above is the result of a CI run that does two builds in parallel (keyring disabled / keyring enabled), which means that one of the builds will overwrite the other one. (I should perhaps fix that sometime..)  
The release builds for Windows always have the keyring feature enabled.
