### ISSUE TITLE
Failing to download specific resources

### ISSUE THREAD

**Issue by 74naUM2EMP** [FliegendeWurst/KIT-ILIAS-downloader#15]
Versions 0.2.17 or later seem to have issues with downloading some resources. These are consistent over multiple runs of the downloader.

Example:
```
Syncing /[path]/Einführung in die Technische Mechanik I: Statik und Festigkeitslehre/Übungsunterlagen/Übung 3: failed to process URL

Caused by:
    0: error sending request for url (https://ilias.studium.kit.edu/ilias.php?ref_id=1470958&cmd=view&cmdClass=ilrepositorygui&cmdNode=uk&baseClass=ilrepositorygui): http2 error: protocol error: not a result of an error
    1: http2 error: protocol error: not a result of an error
```

Version 0.2.16 is still working correctly.

**Comment by FliegendeWurst** [comment]
Thanks for the report. I actually experience the same issue (on a different object of course).  
The same error happened randomly before: https://github.com/FliegendeWurst/KIT-ILIAS-downloader/issues/6#issuecomment-766412859

My guess is that bcc16f1ec51e994130e36b9b294bd68ca6196d9f made the downloader deterministic enough for this error to occur consistently.

https://github.com/hyperium/hyper/issues/2500 is probably related.

**Comment by FliegendeWurst** [comment]
d5037f9ae765ed566f3de400b19bb9ceda4a59e1 should fix this issue by retrying the download if this error occurs.

I haven't tried the fix myself, but an experimental build is available: https://github.com/FliegendeWurst/KIT-ILIAS-downloader/suites/2732740449/artifacts/60328624

**Comment by 74naUM2EMP** [comment]
Sadly, this patch results in it finishing instantly

```
Logging into ILIAS using KIT account..
Logging into Shibboleth..
Logging into ILIAS..
Logged in!
[1/1] done
```

**Comment by FliegendeWurst** [comment]
Just fixed that, here's a new build: https://github.com/FliegendeWurst/KIT-ILIAS-downloader/suites/2733123585/artifacts/60338377

**Comment by 74naUM2EMP** [comment]
That seems to have done the trick, thx.
