### ISSUE TITLE
Hilfestellung Herunterladen

### ISSUE THREAD

**Issue by TheMEGuy** [FliegendeWurst/KIT-ILIAS-downloader#16]
Hi,

ich bin was Git angeht ein blutiger Anfänger(mehr als das), möchte aber trotzdem nicht alles per Hand aus meinen Iliaskursen downloaden.

Ich habe Rust heruntergeladen und habe den commands cargo install --all-features --path . eingegeben. 
Zurückbekommen habe ich den folgenden Fehler: 

![grafik](https://user-images.githubusercontent.com/74842320/118274057-f7dd5780-b4c4-11eb-8818-d448c6adae15.png)

Könnt ihr mir dabei helfen?

Vielen Dank

**Comment by FliegendeWurst** [comment]
Für Windows und Linux lade ich hier direkt ausführbare Programme hoch: https://github.com/FliegendeWurst/KIT-ILIAS-downloader/releases  
Nur macOS-Nutzer müssen das Programm selbst kompilieren.

Der Fehler zu "link.exe" kann vermutlich mit der Installation von Visual Studio behoben werden.
