### ISSUE TITLE
Package built with `--release` sometimes terminates when starting a sync

### ISSUE THREAD

**Issue by Ma27** [FliegendeWurst/KIT-ILIAS-downloader#2]
I occasionally have a fairly weird problem with this package when using a version that was built with `--release`. Unfortunately I'm not entirely sure anymore when exactly it occurred at first. Unfortunately I'm pretty sure that bisecting might be kinda hard since some fixes for reading content from ILIAS were recently added.

To be precise, the problem I have is that sometimes running `KIT-ILIAS-downloader` (built with `--release`) doesn't download content, but instead stops with several errors or completely silently (I didn't manage to find a reasonable pattern yet, unfortunately):

```
# silent termination
λ ma27 [Uni/Studium/ILIAS] → ~/Projects/kit-ilias-downloader/target/release/KIT-ILIAS-downloader  --output `pwd` -vvv |tee out
Logging into ILIAS using KIT account..
Logging into Shibboleth..
Logging into ILIAS..
Logged in!
Downloading https://ilias.studium.kit.edu/ilias.php?baseClass=ilPersonalDesktopGUI&cmd=jumpToSelectedItems
```

```
λ ma27 [Uni/Studium/ILIAS] → ~/Projects/kit-ilias-downloader/target/release/KIT-ILIAS-downloader  --output `pwd` -vvv |tee out
Logging into ILIAS using KIT account..
Logging into Shibboleth..
Logging into ILIAS..
Logged in!
Downloading https://ilias.studium.kit.edu/ilias.php?baseClass=ilPersonalDesktopGUI&cmd=jumpToSelectedItems
Ignored Tutorium 4
Ignored Aufgabenblätter
Ignored Lineare Algebra I e-m
Ignored Softwaretechnik I mit Übung
Syncing course Datenbanksysteme
 URL: https://ilias.studium.kit.edu/ilias.php?ref_id=1101554&cmdClass=ilrepositorygui&cmdNode=ug&baseClass=ilrepositorygui
Syncing /home/ma27/Documents/Uni/Studium/ILIAS/Datenbanksysteme: failed to process URL

Caused by:
    background task failed
Syncing course Einführung in Rechnernetze
 URL: https://ilias.studium.kit.edu/ilias.php?ref_id=1099996&cmdClass=ilrepositorygui&cmdNode=ug&baseClass=ilrepositorygui
Syncing /home/ma27/Documents/Uni/Studium/ILIAS/Einführung in Rechnernetze: failed to process URL

Caused by:
    background task failed
Ignored Interfakultatives Forum
Ignored Übungsblattabgabe
Ignored Übungsblatt 1
Ignored Übungsblatt 2
Ignored Grundbegriffe der Informatik (2018-2019)
Ignored Betriebssysteme WS 19-20
Syncing course Betriebssysteme WS 20-21
 URL: https://ilias.studium.kit.edu/ilias.php?ref_id=1240138&cmdClass=ilrepositorygui&cmdNode=ug&baseClass=ilrepositorygui
Syncing /home/ma27/Documents/Uni/Studium/ILIAS/Betriebssysteme WS 20-21: failed to process URL

Caused by:
    background task failed
```

However, *sometimes*(tm) the sync works perfectly fine.

The reason why I emphasized that this only occurs with `--release` is that I *don't* have these problems whenever I build this with `--debug`. The issue can be discovered on my machine as soon as `opt-level` is at least `1`, it doesn't matter whether debug symbols are present or not.

Details about my machine:

* OS: NixOS 20.09 (Linux 5.8.18, glibc 2.31)
* Built with `rustc` 1.45.2 & `cargo` 1.45.1

**Comment by FliegendeWurst** [comment]
Thanks for the report. I actually experienced the second issue a few times already.

Someone else had similar errors (https://github.com/tokio-rs/tokio/issues/2247#issuecomment-589394508):

> I eventually figured out this was a case of not keeping the top-level task waiting on the spawned tasks, resulting in the runtime shutting down and those tasks failing midway through (with the above error).

The same is probably happening here.

**Comment by FliegendeWurst** [comment]
I made some changes in https://github.com/FliegendeWurst/KIT-ILIAS-downloader/commit/09f69b9efd6da4d470aaf4d8c4cf9ac1366b612f that should fix this issue.

**Comment by Ma27** [comment]
Thanks a lot for the quick response and fix! With 09f69b9efd6da4d470aaf4d8c4cf9ac1366b612f and 377cef7cf2e9b9e36718d22c273b67bf02480157 applied, the sync works fine and the issue described above appears gone.

Unfortunately, the termination doesn't seem to work properly: as soon as all of my courses are synced, the program doesn't terminate until I do it manually with a SIGINT (`<C-c>`). This can be reproduced whenever I run it.

To make sure that the underlying problem is not a slow internet on my side (or a slow ILIAS on the other side :p) I checked what the program is doing like this:

```
λ ma27 [~] → pgrep -a KIT-ILIAS-
8533 /nix/store/vb3q482bh6qbq1cixjyz7rgssmx45b0m-kit-ilias-downloader/bin/KIT-ILIAS-downloader --output /home/ma27/Documents/Uni/Studium/ILIAS -vvv

λ ma27 [~] → pstree 8533
KIT-ILIAS-downl───8*[{KIT-ILIAS-downl}]

λ ma27 [~] → strace -ftp 8533
strace: Process 8533 attached with 9 threads
[pid  8541] 16:10:05 futex(0x556ae813b5bc, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  8540] 16:10:05 futex(0x556ae813db7c, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  8539] 16:10:05 futex(0x556ae813c8f8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  8538] 16:10:05 futex(0x556ae813bec8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  8537] 16:10:05 futex(0x556ae81367b8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  8536] 16:10:05 futex(0x556ae813d238, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  8535] 16:10:05 futex(0x556ae8136a48, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  8534] 16:10:05 epoll_wait(3,  <unfinished ...>
[pid  8533] 16:10:05 futex(0x556ae813fc9c, FUTEX_WAIT_PRIVATE, 0, NULL^Cstrace: Process 8533 detached
 <detached ...>
strace: Process 8534 detached
strace: Process 8535 detached
strace: Process 8536 detached
strace: Process 8537 detached
strace: Process 8538 detached
strace: Process 8539 detached
strace: Process 8540 detached
strace: Process 8541 detached

λ ma27 [~] → ps aux |grep 8533
ma27      1020  0.0  0.0 217964  1652 pts/6    S+   16:15   0:00 grep --color 8533
ma27      8533  1.3  0.2 623312 33072 pts/7    Sl+  15:16   0:46 /nix/store/vb3q482bh6qbq1cixjyz7rgssmx45b0m-kit-ilias-downloader/bin/KIT-ILIAS-downloader --output /home/ma27/Documents/Uni/Studium/ILIAS -vvv
```

As you can see in the output of `ps aux`, the process is actually sleeping.

Did I do something wrong? Or in case that's an issue, do you need any additional information to investigate? :)

**Comment by FliegendeWurst** [comment]
That happened because the main function waited for new tasks after all the other tasks were already complete.. quite a silly mistake :)

It should be fixed in the latest commit https://github.com/FliegendeWurst/KIT-ILIAS-downloader/commit/7d4b9279eebaff46ab017ea8ce3913d52bb70722.

**Comment by Ma27** [comment]
I can confirm that this issue is solved now as well. Thanks a lot for your efforts!
