### ISSUE TITLE
failed to process URL when trying to download videos

### ISSUE THREAD

**Issue by DM2PF** [FliegendeWurst/KIT-ILIAS-downloader#26]
Hi,

I get the following error for each video the program is trying to download:

```
Syncing /storage/ILIAS/######/######.mp4: failed to process URL

Caused by:
    0: error sending request for url (https://oc-delivery.bibliothek.kit.edu/staticfiles/mh_default_org/api/######/######/######.mp4?policy=######&keyId=default&signature=######): error trying to connect: tcp connect error: Host is unreachable (os error 113)
    1: error trying to connect: tcp connect error: Host is unreachable (os error 113)
    2: tcp connect error: Host is unreachable (os error 113)
    3: Host is unreachable (os error 113)
```

This occurs to me for several (all) lectures I tried. Non-video content is downloading perfectly fine, and I can watch the videos in a browser.

I tried versions v0.2.24, v0.2.21 and v0.2.16.

It seems like `youtube-dl` is also having the same problems (I used this method before using your script and it worked back then):

```
youtube-dl https:\/\/oc-delivery.bibliothek.kit.edu\/staticfiles\/mh_default_org\/api\/######\/######.mp4\?policy\=######\&keyId\=default\&signature\=######
[generic] ######: Requesting header
WARNING: Could not send HEAD request to https://oc-delivery.bibliothek.kit.edu/staticfiles/mh_default_org/api/######/######/######.mp4?policy=######&keyId=default&signature=######: <urlopen error [Errno 113] No route to host>
[generic] ######: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 113] No route to host> (caused by URLError(error(113, 'No route to host'),))
```

In fact, I cant even ping `oc-delivery.bibliothek.kit.edu`...

Unfortunately, I din't have the time to dig deeper into this, but maybe you already have a clue.

**Comment by FliegendeWurst** [comment]
Hi, just tried downloading a video. It works for me.

**Comment by DM2PF** [comment]
It just worked on a different machine in a different network... Strange, might be some KIT server vodoo as well.

**Comment by FliegendeWurst** [comment]
Closing this issue since it was probably just a temporary network glitch..
