### ISSUE TITLE
Update for Ilias 7

### ISSUE THREAD

**Issue by 74naUM2EMP** [FliegendeWurst/KIT-ILIAS-downloader#27]
The instance has been updated to Ilias version 7. The “personal desktop” now seems to be equivalent to “Dashboard -> Favorites”. Consequentially normal usage of the program is not possible. Explicitly specified downloads with `--sync-url` still work sometimes if you use the URL from the Info tab. Additionally videos have also been changed and can’t be downloaded anymore.

**Comment by FliegendeWurst** [comment]
Yes, I've just noticed the update as well. I'll list some TODO items in this comment.

- [ ] Dashboard favorites extraction
- [ ] Video downloads

**Comment by FliegendeWurst** [comment]
0.3.0 is out and supports downloading the dashboard favorites!

**Comment by 74naUM2EMP** [comment]
Wow, that was quick and it works. Thx

**Comment by funnym0nk3y** [comment]
I don't know how exactly it is implemented, but may be consider a change from favorites to my courses and groups below. That circumvents problems if the course is not marked as favorite.

**Comment by funnym0nk3y** [comment]
I' having some issues with downloading video files: 

```
Syncing \\?\C:\Users\Michael\OneDrive\Studium\ILIAS_downloader_ingestion\2511500 – Maschinelles Lernen 1 - Grundverfahren\Vorlesungsaufzeichnungen: failed to process URL

Caused by:
    failed to find xoct event link
```

**Comment by 74naUM2EMP** [comment]
> I don't know how exactly it is implemented, but may be consider a change from favorites to my courses and groups below. That circumvents problems if the course is not marked as favorite.

I'd advise against that. This would download every course you're a member of. It would be very annoying to exclude all the old courses with `.iliasignore` rather than using the Ilias interface. Additionally "favorites" is equivalent to the "personal desktop" from Ilias 5, so functionality wise nothing has changed. If you want to to download every course you're in, you just need to mark them as favorite once.

**Comment by funnym0nk3y** [comment]
Well, in the version for ILIAS 5 this was the case. Everything was downloaded except the files excluded by the `.iliasignore`. Besides that: You don't have to exclude every old course. As it uses `.gitignore` syntax you can just block all the courses and whitelist the ones you need via 

```
/*/
!/your_course/
/your_course/folder_to_exclude/
```

**Comment by 74naUM2EMP** [comment]
Still using `.iliasignore` to mimic the favorites section is still rather annoying. Maybe it'd be best to just add another flag for downloading only favorites / all courses (and defaulting to one of them).

**Comment by FliegendeWurst** [comment]
In the next version you'll be able to download this page: https://ilias.studium.kit.edu/ilias.php?cmdClass=ilmembershipoverviewgui&cmdNode=iy&baseClass=ilmembershipoverviewgui (which contains every course you joined)

**Comment by FliegendeWurst** [comment]
> I'm having some issues with downloading video files:
> 
> ```
> Syncing \\?\C:\Users\funnym0nk3y\OneDrive\Studium\ILIAS_downloader_ingestion\2511500 – Maschinelles Lernen 1 - Grundverfahren\Vorlesungsaufzeichnungen: failed to process URL
> 
> Caused by:
>     failed to find xoct event link
> ```

Works for me (just joined that course to test it).

**Comment by funnym0nk3y** [comment]
@FliegendeWurst I still have this issue with version 0.3.1 with all my courses. Is there any information I can provide to solve this?

**Comment by funnym0nk3y** [comment]
I did some digging what could cause that problem and found a bug in the regex. See PR
