### ISSUE TITLE
Add option to download all courses

### ISSUE THREAD

**Issue by SolidTux** [FliegendeWurst/KIT-ILIAS-downloader#30]
It would be great to have an easier to access option to just download everything. Currently this works for me by using the URL `https://ilias.studium.kit.edu/ilias.php?cmdClass=ilmembershipoverviewgui&cmdNode=iy&baseClass=ilmembershipoverviewgui`, but having a command line argument for this would be nice.

**Comment by FliegendeWurst** [comment]
Thanks for the suggestion, I added `--all` to download all courses in 0.3.3.

My main concern with this option is that the URL will change when ILIAS is updated.. (at least the "cmdNode=iy" part)

**Comment by SolidTux** [comment]
Awesome! I got that link from "Meine Kurse und Gruppen", maybe there's a way to scrape that link?
