### ISSUE TITLE
Cant login to ILIAS

### ISSUE THREAD

**Issue by el14s7** [FliegendeWurst/KIT-ILIAS-downloader#5]
When I try to log in to ILIAS with your tool, it always shows the same error:

![image](https://user-images.githubusercontent.com/21080573/103619765-97e10e00-4f32-11eb-8b52-b5295ffd010a.png)

Although I can login with the Same credentials to the ILIAS website.

Probably that error has already been fixed by Ma27, but is released yet.

Thanks for your help

**Comment by FliegendeWurst** [comment]
The error is already fixed. I'll release a new version in a few minutes.

**Comment by el14s7** [comment]
Works. Thank you!
