### ISSUE TITLE
Issue with video list link (cmdNode changed)

### ISSUE THREAD

**Issue by funnym0nk3y** [FliegendeWurst/KIT-ILIAS-downloader#7]
I get the error that there is a failure in the download of the videos. 

```
Loading https://ilias.studium.kit.edu/ilias.php?ref_id=1339852&cmdClass=xocteventgui&cmdNode=n8:n0:14q&baseClass=ilObjPluginDispatchGUI&lang=de&limit=20&cmd=asyncGetTableGUI&cmdMode=asynch
Syncing \\?\path-to-folder\ILIAS_downloader_ingestion\course: failed to process URL

Caused by:
    video list link not found
```

**Comment by funnym0nk3y** [comment]
On the ILIAS Forum they suggested to use a goto-link. Don't know how this integrates though...

**Comment by FliegendeWurst** [comment]
The link to the lectures redirects to the correct page. That would automatically work with future updates too.

**Comment by funnym0nk3y** [comment]
What is the `cmdNode` parameter even?

**Comment by FliegendeWurst** [comment]
It's mentioned in their [security documentation](https://github.com/ILIAS-eLearning/ILIAS/blob/5ed4fecd55e4b706fa1144a0eed667a40a171f69/docs/development/input-processing.md): 

> Passing routing information to find out which GUI-classes should be executed to build a view or perform some action via $_GET["baseClass"], $_GET["cmdClass"] and **$_GET["cmdNode"]**.

That means the parameter value may change when the system is updated. We shouldn't hardcode these values.

**Comment by funnym0nk3y** [comment]
ILIAS has a SOAP interface, maybe that is usable instead of webcrawling (that's what is used, right?).

**Comment by FliegendeWurst** [comment]
I tried savon, but it didn't really work on the [WSDL](https://ilias.studium.kit.edu/webservice/soap/server.php?wsdl).

**Comment by funnym0nk3y** [comment]
What about gSOAP with a C FFI?
